laptop_ecommerce/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from management import views
from management.views import custom_403_view

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', views.home, name='home'),

    path('register/', views.register, name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(next_page='home'), name='logout'),

    path('addlaptop', views.add_laptop, name='add_laptop'),
    path('laptopslist/', views.LaptopsListView.as_view(), name='laptops_list'),
    path('laptopdetail/<pk>/', views.LaptopDetailView.as_view(), name='laptop_detail'),
    path('laptopdelete/<pk>/', views.LaptopDeleteView.as_view(), name='laptop_delete'),
    path('laptopupdate/<pk>/', views.LaptopUpdateView.as_view(), name='laptop_update'),

    path('search', views.search, name='search'),

    path('sellerdashboard/<int:seller_id>/', views.seller_dashboard, name='seller_dashboard'),

    path('laptopreview/<int:laptop_id>/', views.add_laptop_review, name='laptop_review'),
    path('laptopdetail/<int:laptop_id>/reviews', views.laptop_and_seller_reviews_list, name='laptop_and_seller_reviews_list'),
    path('sellerreview/<int:seller_id>/<int:laptop_id>', views.add_seller_review, name='seller_review'),


    path('add_to_cart/<int:laptop_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/increase/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom errors pages
handler403 = custom_403_view

management/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings

# Create your models here.
class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = (
        ('buyer', 'Acquirente'),
        ('seller', 'Fornitore'),
    )
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)


class Laptop(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200, blank=True, null=True)
    processor_brand = models.CharField(max_length=100)
    processor_model = models.CharField(max_length=100)
    ram = models.IntegerField()
    storage = models.IntegerField()
    display_inches = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='laptops/', blank=True, null=True)

    CATEGORY_CHOICES = (
        ('', 'Select Category'),
        ('BL', 'Budget laptop'),
        ('HE', 'High end laptop'),
        ('CO', 'Convertible or 2-in-1'),
        ('GA', 'Gaming'),
        ('EN', 'Enterprise'),
    )
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)

    seller = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)

    @property
    def avg_rating(self):
        laptop_reviews = self.laptopreview_set.all()
        if laptop_reviews.exists():
            avg = sum(laptop_review.rating for laptop_review in laptop_reviews) / laptop_reviews.count()
            return round(avg, 2)
        return 0


class LaptopReview(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    laptop = models.ForeignKey(Laptop, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, str(i)) for i in range(1, 6)])
    description = models.TextField(max_length=200, blank=True, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user', 'laptop'),)

    def __str__(self):
        return f"{self.user}'s review for {self.laptop.name} {self.laptop.display_inches}'' {self.laptop.processor_brand} {self.laptop.ram}/{self.laptop.storage} by {self.laptop.seller}"


class SellerReview(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='seller_reviews')
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_reviews')
    rating = models.PositiveIntegerField(choices=[(i, str(i)) for i in range(1, 6)])
    description = models.TextField(max_length=200, blank=True, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}'s review for {self.seller}"


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    laptop = models.ForeignKey(Laptop, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)
    is_shipped = models.BooleanField(default=False)
    is_received = models.BooleanField(default=False)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    laptop = models.ForeignKey(Laptop, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

management/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.shortcuts import render, redirect, get_object_or_404
from numpy.ma.extras import average

from .forms import CustomUserCreationForm, LaptopForm, SearchForm, LaptopReviewForm, SellerReviewForm
from .models import CustomUser, Laptop, LaptopReview, SellerReview, Cart, CartItem, Order, OrderItem
from .decorators import seller_required, SellerRequiredMixin
from .recommendations import get_recommendations
from django.db.models import Avg, Sum, F


# Create your views here.

def custom_403_view(request, exception):
    return render(request, 'management/403.html', status=403)


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = CustomUserCreationForm()

    return render(request, 'registration/register.html', {'form': form})

class CustomLoginView(LoginView):
    template_name = 'registration/login.html'

class CustomLogoutView(LogoutView):
    template_name = 'registration/logged_out.html'


def home(request):
    recommended_laptops = get_recommendations(request.user)
    most_highly_rated = Laptop.objects.annotate(
        avg = Avg('laptopreview__rating')
    ).order_by('-avg')[:6]
    return render(request, 'management/home.html', {'recommended_laptops': recommended_laptops, 'most_highly_rated': most_highly_rated})


class LaptopsListView(ListView):
    model = Laptop
    template_name = 'management/laptops_list.html'
    title = 'Laptops list'

    def get_queryset(self):
        return Laptop.objects.order_by('seller')

@login_required
@seller_required
def add_laptop(request):
    if request.method == 'POST':
        form = LaptopForm(request.POST, request.FILES)
        if form.is_valid():
            laptop = form.save(commit=False)
            laptop.seller = request.user
            laptop.save()
            messages.success(request, 'Laptop aggiunto con successo')

            seller_id = request.user.id
            return redirect('seller_dashboard', seller_id)
        else:
            messages.error(request, 'Laptop non creato')
    else:
        form = LaptopForm()
    return render(request, 'management/add_laptop.html', {'form': form})

class LaptopDetailView(DetailView):
    model = Laptop
    template_name = 'management/laptop_detail.html'

class LaptopDeleteView(SellerRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Laptop
    template_name = 'management/laptop_delete.html'
    def get_success_url(self):
        seller_id = self.request.user.id
        return reverse('seller_dashboard', kwargs={'seller_id': seller_id})

class LaptopUpdateView(SellerRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Laptop
    template_name = 'management/laptop_update.html'
    form_class = LaptopForm

    def get_success_url(self):
        pk = self.get_context_data()["object"].pk
        return reverse("laptop_detail", kwargs={'pk': pk})


def search(request):
    ctx = None

    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            processor_brand = form.cleaned_data.get("processor_brand")
            ram = form.cleaned_data.get("ram")
            storage = form.cleaned_data.get("storage")
            display_inches = form.cleaned_data.get("display_inches")
            price = form.cleaned_data.get("price")
            category = form.cleaned_data.get("category")

            laptops = Laptop.objects.all()
            if name:
                laptops = laptops.filter(name__icontains=name)
            if processor_brand:
                laptops = laptops.filter(processor_brand__iexact=processor_brand)
            if ram:
                laptops = laptops.filter(ram__iexact=ram)
            if storage:
                laptops = laptops.filter(storage__iexact=storage)
            if display_inches:
                laptops = laptops.filter(display_inches__iexact= display_inches)
            if price:
                laptops = laptops.filter(price__lte=price)
            if category:
                laptops = laptops.filter(category__icontains=category)

            ctx = {
                'form': form,
                'laptops': laptops,
            }

    return render(request, 'management/search.html', ctx)


@login_required
@seller_required
def seller_dashboard(request, seller_id):
    seller_reviews = SellerReview.objects.filter(seller_id=seller_id)

    # Stats vendite
    total_sales = OrderItem.objects.filter(laptop__seller=seller_id).aggregate(
        total_sales = Sum(F('price') * F('quantity'))
    )['total_sales'] or 0
    total_sales = round(total_sales, 2)

    total_orders = OrderItem.objects.filter(laptop__seller=seller_id).aggregate(
        total_quantity_sold=Sum('quantity')
    )['total_quantity_sold'] or 0

    top_selling_laptops = (Laptop.objects.filter(seller_id=seller_id, orderitem__isnull=False)
        .annotate(total_sold=Sum('orderitem__quantity'))
        .order_by('-total_sold'))

    ctx = {
        "object_list" : Laptop.objects.filter(seller=seller_id),
        "seller_reviews": seller_reviews,
        'total_sales': total_sales,
        'total_orders': total_orders,
        'top_selling_laptops': top_selling_laptops,
    }
    return render(request, 'management/seller_dashboard.html', context=ctx)


@login_required
def add_laptop_review(request, laptop_id):
    if request.user.user_type != 'buyer':
        messages.error(request, 'I fornitori non posso aggiungere recensioni ai laptop')
        return redirect('home')
    laptop = get_object_or_404(Laptop, id=laptop_id)
    if LaptopReview.objects.filter(laptop=laptop, user=request.user).exists():
        messages.error(request, 'Hai già recensito questo laptop.')
        return redirect('laptop_detail', laptop_id)

    if request.method == 'POST':
        form = LaptopReviewForm(request.POST)
        if form.is_valid():
            laptop_review = form.save(commit=False)
            laptop_review.user = request.user
            laptop_review.laptop = laptop
            laptop_review.save()
            messages.success(request, 'Recensione al laptop creata con successo')
            return redirect('laptop_detail', laptop_id)
    else:
        form = LaptopReviewForm()
    return render(request, 'management/laptop_review.html', {'form': form, 'laptop_id': laptop_id})

@login_required
def laptop_and_seller_reviews_list(request, laptop_id):
    laptop = get_object_or_404(Laptop, id=laptop_id)
    seller = get_object_or_404(CustomUser, id=laptop.seller_id)
    return render(request, 'management/laptop_and_seller_reviews_list.html', {'laptop': laptop, 'seller': seller})


@login_required
def add_seller_review(request, seller_id, laptop_id):
    if request.user.user_type != 'buyer':
        messages.error(request, 'I fornitori non posso aggiungere recensioni ai fornitori')
        return redirect('home')
    seller = get_object_or_404(CustomUser, id=seller_id)
    if request.method == 'POST':
        form = SellerReviewForm(request.POST)
        if form.is_valid():
            seller_review = form.save(commit=False)
            seller_review.user = request.user
            seller_review.seller = seller
            seller_review.save()
            messages.success(request, 'Recensione al fornitore creata con successo')
            return redirect('laptop_detail', laptop_id)
    else:
        form = SellerReviewForm()
    return render(request, 'management/seller_review.html', {'form': form, 'seller': seller, 'laptop_id': laptop_id})


@login_required
def add_to_cart(request, laptop_id):
    if request.user.user_type != 'buyer':
        messages.error(request, 'I fornitori non possono aggiungere laptop al carrello')
        return redirect('home')

    laptop = get_object_or_404(Laptop, id=laptop_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, item_created = CartItem.objects.get_or_create(cart=cart, laptop=laptop)

    if not item_created:
        cart_item.quantity += 1
        cart_item.save()

    messages.success(request, "Laptop aggiunto al carrello con successo.")
    return redirect('laptop_detail', laptop_id)

@login_required
def cart_detail(request):
    if request.user.user_type != 'buyer':
        messages.error(request, 'I fornitori non possono accedere al carrello')
        return redirect('home')

    cart = Cart.objects.filter(user=request.user).first()
    cart_items = cart.cartitem_set.all() if cart else []
    return render(request, 'management/cart_detail.html', {'cart_items': cart_items})


@login_required
def increase_quantity(request, item_id):
    if request.user.user_type != 'buyer':
        messages.error(request, 'I fornitori non possono aumentare di quantità un elemento del carrello')
        return redirect('home')

    cart_item = get_object_or_404(CartItem, id=item_id, cart__user=request.user)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('cart_detail')

@login_required
def decrease_quantity(request, item_id):
    if request.user.user_type != 'buyer':
        messages.error(request, 'I fornitori non possono diminuire di quantità un elemento del carrello')
        return redirect('home')

    cart_item = get_object_or_404(CartItem, id=item_id, cart__user=request.user)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:

management/templates/management/add_laptop.html
{% extends "base.html" %}

{% block title %}Aggiungi Laptop - E-Laptop{% endblock %}

{% block content %}
<div class="container my-5">
    <h2 class="text-center mb-4">Aggiungi un nuovo Laptop</h2>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" class="bg-light p-4 rounded shadow-sm" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- Bootstrap form styling -->
                <div class="mb-3">
                    {{ form.as_p }}
                </div>

                <!-- Submit button -->
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary btn-block">Aggiungi Laptop</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

management/templates/management/cart_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css">

<div class="container mt-5">
    <h2>Carrello</h2>
    <ul class="list-group">
        {% for item in cart_items %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    {% if item.laptop.image %}
                    	<img src="{{ item.laptop.image.url }}" alt="{{ item.laptop.name }}" style="width: 50px; height: auto; margin-right: 10px;">
                    {% endif %}
                    <span>{{ item.laptop.name }}</span>
                </div>
                <div class="d-flex align-items-center">
                    <span>{{ item.laptop.price }} €</span>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <span class="mr-3">Quantità: {{ item.quantity }}</span>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    <!-- Pulsanti per modificare quantità e rimuovere -->
                    <a href="{% url 'increase_quantity' item.id %}" class="btn btn-sm btn-success ml-2">
                        <i class="bi bi-plus-lg"></i>
                    </a>
                    <a href="{% url 'decrease_quantity' item.id %}" class="btn btn-sm btn-warning ml-2">
                        <i class="bi bi-dash-lg"></i>
                    </a>
                    <a href="{% url 'remove_from_cart' item.id %}" class="btn btn-sm btn-danger ml-2">
                        <i class="bi bi-trash"></i>
                    </a>
                </div>
            </li>
        {% empty %}
            <li class="list-group-item">Il carrello è vuoto.</li>
        {% endfor %}
    </ul>
    <div class="d-flex justify-content-end mt-3">
        <a href="{% url 'checkout' %}" class="btn btn-primary">Checkout</a>
    </div>
</div>
{% endblock %}

management/templates/management/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h2>Riepilogo Ordine</h2>
    <ul class="list-group">
        {% for item in cart_items %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    {% if item.laptop.image %}
                    	<img src="{{ item.laptop.image.url }}" alt="{{ item.laptop.name }}" style="width: 50px; height: auto; margin-right: 10px;">
                    {% endif %}
                    <span>{{ item.laptop.name }}</span>
                </div>
                <div class="d-flex align-items-center">
                    <span class="mr-3">Quantità: {{ item.quantity }}</span>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <span>{{ item.laptop.price }} €</span>
                </div>
            </li>
        {% endfor %}
    </ul>
    <h4 class="mt-4">Totale: {{ total_amount|floatformat:2 }} €</h4>
    <div class="d-flex justify-content-end mt-3">
        <a href="{% url 'cart_detail' %}" class="btn btn-secondary mr-2">Torna al Carrello</a>
        &nbsp;&nbsp;&nbsp;
        <a href="{% url 'confirm_order' %}" class="btn btn-success">Conferma Ordine</a>
    </div>
</div>
{% endblock %}

management/templates/management/home.html
{% extends "base.html" %}

{% block title %}Home - E-Laptop{% endblock %}

{% block content %}
    <div class="container-fluid bg-primary text-white text-center py-4">
        <h1>Benvenuti su E-Laptop</h1>
        <p>Trova i migliori laptop, computer e accessori per tutte le tue esigenze</p>
        <!--<a href="#" class="btn btn-light mt-3">Scopri di più</a>   -->
    </div>

    {% if user.is_authenticated %}
        {% if user.user_type == 'buyer'%}
            <h2 class="text-center my-5">Utenti simili a te hanno apprezzato:</h2>
        {% endif %}
    {% else %}
        <h2 class="text-center my-5">Registrati o accedi come acquirente per ricevere consigli sugli acquisti</h2>
    {% endif %}

    <div class="row">
        {% for laptop in recommended_laptops %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    {% if laptop.image %}
                        <img src="{{ laptop.image.url }}" class="card-img-top" alt="{{ laptop.name }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ laptop.name }}    |    €{{ laptop.price }} </h5>
                        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
                        <i class="fas fa-star text-warning"></i> {{ laptop.avg_rating }}
                        <p class="card-text">{{ laptop.display_inches }}'', {{ laptop.processor_brand }} {{ laptop.processor_model }} | {{ laptop.ram }}, {{ laptop.storage }} </p>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'laptop_detail' laptop.id %}" class="btn btn-primary">Visualizza Dettagli</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


    <h2 class="text-center my-5">I più apprezzati:</h2>
    <div class="row">
        {% for laptop in most_highly_rated %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    {% if laptop.image %}
                        <img src="{{ laptop.image.url }}" class="card-img-top" alt="{{ laptop.name }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ laptop.name }}    |    €{{ laptop.price }} </h5>
                        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
                        <i class="fas fa-star text-warning"></i> {{ laptop.avg_rating }}
                        <p class="card-text">{{ laptop.display_inches }}'', {{ laptop.processor_brand }} {{ laptop.processor_model }} | {{ laptop.ram }}, {{ laptop.storage }} </p>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'laptop_detail' laptop.id %}" class="btn btn-primary">Visualizza Dettagli</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

management/templates/management/laptop_review.html
{% extends "base.html" %}

{% block title %}Recensione al Laptop - E-Laptop{% endblock %}

{% block content %}
<div class="container my-5">
    <h2 class="text-center mb-4">Recensione al Laptop</h2>
    
    <div class="row justify-content-center">
        <div class="col-md-6">
            <!-- Formulario recensione -->
            <form method="post" class="bg-light p-4 rounded shadow-sm">
                {% csrf_token %}
                
                <!-- Campo per il rating -->
                <div class="mb-3">
                    <label for="id_rating" class="form-label">Valutazione</label>
                    <select name="rating" id="id_rating" class="form-select" required>
                        {% for choice in form.fields.rating.choices %}
                            <option value="{{ choice.0 }}" {% if form.rating.value == choice.0 %}selected{% endif %}>{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Campo per la descrizione -->
                <div class="mb-3">
                    <label for="id_description" class="form-label">Descrizione</label>
                    <textarea name="description" id="id_description" cols="80" rows="4" class="form-control">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
                </div>

                <!-- Pulsante per inviare la recensione -->
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary btn-block">Invia Recensione</button>
                    <a href="{% url 'laptop_detail' laptop_id %}" class="btn btn-secondary">Annulla</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

management/templates/management/search.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Cerca</h2>
    <form method="get" action="">

        <div class="form-group mb-3">
            <label for="id_name">Laptop Name</label>
            <input type="text" name="name" class="form-control" id="id_name" maxlength="100" placeholder="Enter laptop name" value="{{ form.name.value|default_if_none:'' }}">
        </div>

        <div class="form-group mb-3">
            <label for="id_processor_brand">Processor Brand</label>
            <select name="processor_brand" class="form-control" id="id_processor_brand">
                {% for value, label in form.fields.processor_brand.choices %}
                    <option value="{{ value }}"
                        {% if form.processor_brand.value == value %}selected{% endif %}>{{ label }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group mb-3">
            <label for="id_ram">RAM (GB)</label>
            <input type="number" name="ram" class="form-control" id="id_ram" placeholder="Enter RAM size in GB" value="{{ form.ram.value }}">
        </div>

        <div class="form-group mb-3">
            <label for="id_storage">Storage (GB)</label>
            <input type="number" name="storage" class="form-control" id="id_storage" placeholder="Enter storage size in GB" value="{{ form.storage.value }}">
        </div>

        <div class="form-group mb-3">
            <label for="id_display_inches">Display Size (inches)</label>
            <input type="number" name="display_inches" class="form-control" id="id_display_inches" placeholder="Enter display size in inches" value="{{ form.display_inches.value }}">
        </div>

        <div class="form-group mb-3">
            <label for="id_price">Budget (€)</label>
            <input type="number" name="price" class="form-control" id="id_price" step="0.01" placeholder="Enter budget" value="{{ form.price.value }}">
        </div>

        <div class="form-group mb-3">
            <label for="id_category">Category</label>
            <select name="category" class="form-control" id="id_category">
                {% for choice, label in form.fields.category.choices %}
                    <option value="{{ choice }}" {% if form.category.value == choice %}selected{% endif %}>{{ label }}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary mt-3">Search</button>

    </form>

</div>




<div class="container my-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="text-center">Risultati ricerca</h2>
    </div>

    <div class="row">
        {% for laptop in laptops %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    {% if laptop.image %}
                        <img src="{{ laptop.image.url }}" class="card-img-top" alt="{{ laptop.name }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ laptop.name }}    |    €{{ laptop.price }} </h5>
                        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
                        <i class="fas fa-star text-warning"></i> {{ laptop.avg_rating }}
                        <p class="card-text">{{ laptop.display_inches }}'', {{ laptop.processor_brand }} {{ laptop.processor_model }} | {{ laptop.ram }}, {{ laptop.storage }} </p>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'laptop_detail' laptop.id %}" class="btn btn-primary">Visualizza Dettagli</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

management/templates/management/seller_review.html
{% extends "base.html" %}

{% block title %}Recensione al Fornitore - E-Laptop{% endblock %}

{% block content %}
<div class="container my-5">
    <h2 class="text-center mb-4">Recensione al Fornitore</h2>
    
    <div class="row justify-content-center">
        <div class="col-md-6">
            <!-- Formulario recensione -->
            <form method="post" class="bg-light p-4 rounded shadow-sm">
                {% csrf_token %}
                
                <!-- Campo per il rating -->
                <div class="mb-3">
                    <label for="id_rating" class="form-label">Valutazione</label>
                    <select name="rating" id="id_rating" class="form-select" required>
                        {% for choice in form.fields.rating.choices %}
                            <option value="{{ choice.0 }}" {% if form.rating.value == choice.0 %}selected{% endif %}>{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Campo per la descrizione -->
                <div class="mb-3">
                    <label for="id_description" class="form-label">Descrizione</label>
                    <textarea name="description" id="id_description" cols="80" rows="4" class="form-control">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
                </div>

                <!-- Pulsante per inviare la recensione -->
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary btn-block">Invia Recensione</button>
                    <a href="{% url 'laptop_detail' laptop_id %}" class="btn btn-secondary">Annulla</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}